/**
 * Default seed data inserted into every newly provisioned tenant schema.
 * This file defines the data — the TenantProvisioningService executes the inserts.
 */

export const DEFAULT_PERMISSIONS = [
  { module: 'employee_management', action: 'view', resource: 'employees', description: 'View employees' },
  { module: 'employee_management', action: 'create', resource: 'employees', description: 'Create employees' },
  { module: 'employee_management', action: 'edit', resource: 'employees', description: 'Edit employees' },
  { module: 'employee_management', action: 'delete', resource: 'employees', description: 'Delete employees' },
  { module: 'employee_management', action: 'export', resource: 'employees', description: 'Export employees' },
  { module: 'employee_management', action: 'import', resource: 'employees', description: 'Import employees' },
  { module: 'employee_management', action: 'view', resource: 'departments', description: 'View departments' },
  { module: 'employee_management', action: 'create', resource: 'departments', description: 'Create departments' },
  { module: 'employee_management', action: 'edit', resource: 'departments', description: 'Edit departments' },
  { module: 'employee_management', action: 'delete', resource: 'departments', description: 'Delete departments' },
  { module: 'employee_management', action: 'view', resource: 'designations', description: 'View designations' },
  { module: 'employee_management', action: 'create', resource: 'designations', description: 'Create designations' },
  { module: 'employee_management', action: 'edit', resource: 'designations', description: 'Edit designations' },
  { module: 'employee_management', action: 'delete', resource: 'designations', description: 'Delete designations' },
  { module: 'employee_management', action: 'view', resource: 'groups', description: 'View groups' },
  { module: 'employee_management', action: 'create', resource: 'groups', description: 'Create groups' },
  { module: 'employee_management', action: 'edit', resource: 'groups', description: 'Edit groups' },
  { module: 'employee_management', action: 'delete', resource: 'groups', description: 'Delete groups' },
  { module: 'employee_management', action: 'view', resource: 'projects', description: 'View projects' },
  { module: 'employee_management', action: 'create', resource: 'projects', description: 'Create projects' },
  { module: 'employee_management', action: 'edit', resource: 'projects', description: 'Edit projects' },
  { module: 'employee_management', action: 'delete', resource: 'projects', description: 'Delete projects' },
  { module: 'employee_management', action: 'view', resource: 'delegations', description: 'View delegations' },
  { module: 'employee_management', action: 'create', resource: 'delegations', description: 'Create delegations' },
  { module: 'employee_management', action: 'edit', resource: 'delegations', description: 'Edit delegations' },
  { module: 'employee_management', action: 'delete', resource: 'delegations', description: 'Delete delegations' },
  { module: 'employee_management', action: 'view', resource: 'reporting_hierarchy', description: 'View reporting hierarchy' },
  { module: 'employee_management', action: 'edit', resource: 'reporting_hierarchy', description: 'Edit reporting hierarchy' },
  { module: 'leave', action: 'view', resource: 'leave_requests', description: 'View leave requests' },
  { module: 'leave', action: 'create', resource: 'leave_requests', description: 'Apply for leave' },
  { module: 'leave', action: 'approve', resource: 'leave_requests', description: 'Approve/reject leave' },
  { module: 'leave', action: 'cancel', resource: 'leave_requests', description: 'Cancel leave requests' },
  { module: 'leave', action: 'export', resource: 'leave_requests', description: 'Export leave data' },
  { module: 'leave', action: 'view', resource: 'leave_types', description: 'View leave types' },
  { module: 'leave', action: 'create', resource: 'leave_types', description: 'Create leave types' },
  { module: 'leave', action: 'edit', resource: 'leave_types', description: 'Edit leave types' },
  { module: 'leave', action: 'delete', resource: 'leave_types', description: 'Delete leave types' },
  { module: 'leave', action: 'view', resource: 'leave_policies', description: 'View leave policies' },
  { module: 'leave', action: 'create', resource: 'leave_policies', description: 'Create leave policies' },
  { module: 'leave', action: 'edit', resource: 'leave_policies', description: 'Edit leave policies' },
  { module: 'leave', action: 'delete', resource: 'leave_policies', description: 'Delete leave policies' },
  { module: 'leave', action: 'view', resource: 'holidays', description: 'View holidays' },
  { module: 'leave', action: 'create', resource: 'holidays', description: 'Create holidays' },
  { module: 'leave', action: 'edit', resource: 'holidays', description: 'Edit holidays' },
  { module: 'leave', action: 'delete', resource: 'holidays', description: 'Delete holidays' },
  { module: 'attendance', action: 'view', resource: 'attendance', description: 'View attendance' },
  { module: 'attendance', action: 'view', resource: 'team_attendance', description: 'View team attendance' },
  { module: 'attendance', action: 'create', resource: 'regularizations', description: 'Request regularization' },
  { module: 'attendance', action: 'approve', resource: 'regularizations', description: 'Approve regularizations' },
  { module: 'attendance', action: 'export', resource: 'attendance', description: 'Export attendance' },
  { module: 'attendance', action: 'view', resource: 'work_schedule', description: 'View work schedules' },
  { module: 'attendance', action: 'create', resource: 'work_schedule', description: 'Create work schedules' },
  { module: 'attendance', action: 'edit', resource: 'work_schedule', description: 'Edit work schedules' },
  { module: 'attendance', action: 'delete', resource: 'work_schedule', description: 'Delete work schedules' },
  { module: 'time_tracker', action: 'view', resource: 'time_logs', description: 'View time logs' },
  { module: 'time_tracker', action: 'view', resource: 'config', description: 'View time tracker config' },
  { module: 'time_tracker', action: 'create', resource: 'config', description: 'Create time tracker config' },
  { module: 'time_tracker', action: 'edit', resource: 'config', description: 'Edit time tracker config' },
  { module: 'time_tracker', action: 'delete', resource: 'config', description: 'Delete time tracker config' },
  { module: 'time_tracker', action: 'execute', resource: 'sync', description: 'Trigger manual sync' },
  { module: 'performance', action: 'view', resource: 'goals', description: 'View goals' },
  { module: 'performance', action: 'create', resource: 'goals', description: 'Create goals' },
  { module: 'performance', action: 'edit', resource: 'goals', description: 'Edit goals' },
  { module: 'performance', action: 'delete', resource: 'goals', description: 'Delete goals' },
  { module: 'performance', action: 'export', resource: 'goals', description: 'Export goals' },
  { module: 'performance', action: 'view', resource: 'review_cycles', description: 'View review cycles' },
  { module: 'performance', action: 'create', resource: 'review_cycles', description: 'Create review cycles' },
  { module: 'performance', action: 'edit', resource: 'review_cycles', description: 'Edit review cycles' },
  { module: 'performance', action: 'view', resource: 'reviews', description: 'View reviews' },
  { module: 'performance', action: 'create', resource: 'reviews', description: 'Submit reviews' },
  { module: 'files', action: 'view', resource: 'files', description: 'View files' },
  { module: 'files', action: 'create', resource: 'files', description: 'Upload files' },
  { module: 'files', action: 'delete', resource: 'files', description: 'Delete files' },
  { module: 'files', action: 'share', resource: 'files', description: 'Share files' },
  { module: 'compensation', action: 'view', resource: 'salary', description: 'View salary data' },
  { module: 'compensation', action: 'create', resource: 'salary', description: 'Create salary records' },
  { module: 'compensation', action: 'edit', resource: 'salary', description: 'Edit salary records' },
  { module: 'compensation', action: 'view', resource: 'payslips', description: 'View payslips' },
  { module: 'compensation', action: 'create', resource: 'payslips', description: 'Generate payslips' },
  { module: 'compensation', action: 'view', resource: 'appraisals', description: 'View appraisals' },
  { module: 'compensation', action: 'create', resource: 'appraisals', description: 'Create appraisals' },
  { module: 'compensation', action: 'view', resource: 'salary_components', description: 'View salary components' },
  { module: 'compensation', action: 'create', resource: 'salary_components', description: 'Create salary components' },
  { module: 'compensation', action: 'edit', resource: 'salary_components', description: 'Edit salary components' },
  { module: 'compensation', action: 'delete', resource: 'salary_components', description: 'Delete salary components' },
  { module: 'compensation', action: 'export', resource: 'compensation', description: 'Export compensation data' },
  { module: 'recruitment', action: 'view', resource: 'job_openings', description: 'View job openings' },
  { module: 'recruitment', action: 'create', resource: 'job_openings', description: 'Create job openings' },
  { module: 'recruitment', action: 'edit', resource: 'job_openings', description: 'Edit job openings' },
  { module: 'recruitment', action: 'delete', resource: 'job_openings', description: 'Delete job openings' },
  { module: 'recruitment', action: 'view', resource: 'candidates', description: 'View candidates' },
  { module: 'recruitment', action: 'create', resource: 'candidates', description: 'Create candidates' },
  { module: 'recruitment', action: 'edit', resource: 'candidates', description: 'Edit candidates' },
  { module: 'recruitment', action: 'delete', resource: 'candidates', description: 'Delete candidates' },
  { module: 'recruitment', action: 'view', resource: 'interviews', description: 'View interviews' },
  { module: 'recruitment', action: 'create', resource: 'interviews', description: 'Schedule interviews' },
  { module: 'recruitment', action: 'edit', resource: 'interviews', description: 'Edit interviews' },
  { module: 'recruitment', action: 'delete', resource: 'interviews', description: 'Cancel interviews' },
  { module: 'recruitment', action: 'view', resource: 'assessments', description: 'View assessments' },
  { module: 'recruitment', action: 'create', resource: 'assessments', description: 'Create assessments' },
  { module: 'recruitment', action: 'view', resource: 'referrals', description: 'View referrals' },
  { module: 'recruitment', action: 'create', resource: 'referrals', description: 'Submit referrals' },
  { module: 'recruitment', action: 'view', resource: 'offer_letters', description: 'View offer letters' },
  { module: 'recruitment', action: 'create', resource: 'offer_letters', description: 'Create offer letters' },
  { module: 'recruitment', action: 'view', resource: 'pipeline_stages', description: 'View pipeline stages' },
  { module: 'recruitment', action: 'edit', resource: 'pipeline_stages', description: 'Edit pipeline stages' },
  { module: 'onboarding', action: 'view', resource: 'onboarding', description: 'View onboarding records' },
  { module: 'onboarding', action: 'create', resource: 'onboarding', description: 'Create onboarding records' },
  { module: 'onboarding', action: 'edit', resource: 'onboarding', description: 'Edit onboarding records' },
  { module: 'onboarding', action: 'convert', resource: 'onboarding', description: 'Convert to employee' },
  { module: 'onboarding', action: 'view', resource: 'templates', description: 'View onboarding templates' },
  { module: 'onboarding', action: 'create', resource: 'templates', description: 'Create onboarding templates' },
  { module: 'onboarding', action: 'edit', resource: 'templates', description: 'Edit onboarding templates' },
  { module: 'onboarding', action: 'delete', resource: 'templates', description: 'Delete onboarding templates' },
  { module: 'offboarding', action: 'view', resource: 'offboarding', description: 'View offboarding records' },
  { module: 'offboarding', action: 'create', resource: 'offboarding', description: 'Initiate offboarding' },
  { module: 'offboarding', action: 'approve', resource: 'offboarding', description: 'Approve offboarding' },
  { module: 'offboarding', action: 'edit', resource: 'offboarding', description: 'Edit offboarding records' },
  { module: 'offboarding', action: 'view', resource: 'offboarding_templates', description: 'View offboarding templates' },
  { module: 'offboarding', action: 'create', resource: 'offboarding_templates', description: 'Create offboarding templates' },
  { module: 'offboarding', action: 'edit', resource: 'offboarding_templates', description: 'Edit offboarding templates' },
  { module: 'offboarding', action: 'delete', resource: 'offboarding_templates', description: 'Delete offboarding templates' },
  { module: 'reports', action: 'view', resource: 'reports', description: 'View reports' },
  { module: 'reports', action: 'export', resource: 'reports', description: 'Export reports' },
  { module: 'settings', action: 'view', resource: 'settings', description: 'View settings' },
  { module: 'settings', action: 'edit', resource: 'settings', description: 'Edit settings' },
  { module: 'settings', action: 'view', resource: 'rbac', description: 'View roles & permissions' },
  { module: 'settings', action: 'edit', resource: 'rbac', description: 'Edit roles & permissions' },
  { module: 'settings', action: 'view', resource: 'audit_logs', description: 'View audit logs' },
  { module: 'settings', action: 'view', resource: 'notifications', description: 'View notification settings' },
  { module: 'settings', action: 'edit', resource: 'notifications', description: 'Edit notification settings' },
  { module: 'dashboard', action: 'view', resource: 'dashboard', description: 'View dashboard' },
];

export const DEFAULT_ROLES: {
  name: string;
  description: string;
  permissions: 'all' | Array<{ module: string; action: string; resource: string }>;
}[] = [
  {
    name: 'Admin',
    description: 'Full access to every module, every action, every resource. Can configure settings, manage RBAC.',
    permissions: 'all',
  },
  {
    name: 'HR Admin',
    description: 'Employee CRUD, leave approval, attendance, performance, compensation, recruitment, onboarding, offboarding, reports. Cannot modify RBAC or org settings.',
    permissions: [
      ...['view', 'create', 'edit', 'delete', 'export', 'import'].map((a) => ({ module: 'employee_management', action: a, resource: 'employees' })),
      ...['view', 'create', 'edit', 'delete'].flatMap((a) => ['departments', 'designations', 'groups', 'projects', 'delegations'].map((r) => ({ module: 'employee_management', action: a, resource: r }))),
      { module: 'employee_management', action: 'view', resource: 'reporting_hierarchy' },
      { module: 'employee_management', action: 'edit', resource: 'reporting_hierarchy' },
      ...['view', 'create', 'approve', 'cancel', 'export'].map((a) => ({ module: 'leave', action: a, resource: 'leave_requests' })),
      ...['view', 'create', 'edit', 'delete'].flatMap((a) => ['leave_types', 'leave_policies', 'holidays'].map((r) => ({ module: 'leave', action: a, resource: r }))),
      ...['view', 'export'].map((a) => ({ module: 'attendance', action: a, resource: 'attendance' })),
      { module: 'attendance', action: 'view', resource: 'team_attendance' },
      { module: 'attendance', action: 'create', resource: 'regularizations' },
      { module: 'attendance', action: 'approve', resource: 'regularizations' },
      ...['view', 'create', 'edit', 'delete'].map((a) => ({ module: 'attendance', action: a, resource: 'work_schedule' })),
      { module: 'time_tracker', action: 'view', resource: 'time_logs' },
      ...['view', 'create', 'edit', 'delete'].map((a) => ({ module: 'time_tracker', action: a, resource: 'config' })),
      { module: 'time_tracker', action: 'execute', resource: 'sync' },
      ...['view', 'create', 'edit', 'delete', 'export'].map((a) => ({ module: 'performance', action: a, resource: 'goals' })),
      ...['view', 'create', 'edit'].map((a) => ({ module: 'performance', action: a, resource: 'review_cycles' })),
      { module: 'performance', action: 'view', resource: 'reviews' },
      { module: 'performance', action: 'create', resource: 'reviews' },
      ...['view', 'create', 'delete', 'share'].map((a) => ({ module: 'files', action: a, resource: 'files' })),
      ...['view', 'create', 'edit'].map((a) => ({ module: 'compensation', action: a, resource: 'salary' })),
      ...['view', 'create'].map((a) => ({ module: 'compensation', action: a, resource: 'payslips' })),
      ...['view', 'create'].map((a) => ({ module: 'compensation', action: a, resource: 'appraisals' })),
      ...['view', 'create', 'edit', 'delete'].map((a) => ({ module: 'compensation', action: a, resource: 'salary_components' })),
      { module: 'compensation', action: 'export', resource: 'compensation' },
      ...['view', 'create', 'edit', 'delete'].flatMap((a) => ['job_openings', 'candidates', 'interviews'].map((r) => ({ module: 'recruitment', action: a, resource: r }))),
      ...['view', 'create'].flatMap((a) => ['assessments', 'referrals', 'offer_letters'].map((r) => ({ module: 'recruitment', action: a, resource: r }))),
      { module: 'recruitment', action: 'view', resource: 'pipeline_stages' },
      { module: 'recruitment', action: 'edit', resource: 'pipeline_stages' },
      ...['view', 'create', 'edit', 'convert'].map((a) => ({ module: 'onboarding', action: a, resource: 'onboarding' })),
      ...['view', 'create', 'edit', 'delete'].map((a) => ({ module: 'onboarding', action: a, resource: 'templates' })),
      ...['view', 'create', 'approve', 'edit'].map((a) => ({ module: 'offboarding', action: a, resource: 'offboarding' })),
      ...['view', 'create', 'edit', 'delete'].map((a) => ({ module: 'offboarding', action: a, resource: 'offboarding_templates' })),
      { module: 'reports', action: 'view', resource: 'reports' },
      { module: 'reports', action: 'export', resource: 'reports' },
      { module: 'dashboard', action: 'view', resource: 'dashboard' },
    ],
  },
  {
    name: 'HR Manager',
    description: 'Same as HR Admin minus: create salary components, delete employees, manage templates.',
    permissions: [
      ...['view', 'create', 'edit', 'export', 'import'].map((a) => ({ module: 'employee_management', action: a, resource: 'employees' })),
      ...['view', 'create', 'edit'].flatMap((a) => ['departments', 'designations', 'groups', 'projects', 'delegations'].map((r) => ({ module: 'employee_management', action: a, resource: r }))),
      { module: 'employee_management', action: 'view', resource: 'reporting_hierarchy' },
      ...['view', 'create', 'approve', 'cancel', 'export'].map((a) => ({ module: 'leave', action: a, resource: 'leave_requests' })),
      ...['view'].flatMap((a) => ['leave_types', 'leave_policies', 'holidays'].map((r) => ({ module: 'leave', action: a, resource: r }))),
      ...['view', 'export'].map((a) => ({ module: 'attendance', action: a, resource: 'attendance' })),
      { module: 'attendance', action: 'view', resource: 'team_attendance' },
      { module: 'attendance', action: 'create', resource: 'regularizations' },
      { module: 'attendance', action: 'approve', resource: 'regularizations' },
      { module: 'attendance', action: 'view', resource: 'work_schedule' },
      { module: 'time_tracker', action: 'view', resource: 'time_logs' },
      { module: 'time_tracker', action: 'view', resource: 'config' },
      ...['view', 'create', 'edit', 'delete', 'export'].map((a) => ({ module: 'performance', action: a, resource: 'goals' })),
      { module: 'performance', action: 'view', resource: 'review_cycles' },
      { module: 'performance', action: 'view', resource: 'reviews' },
      { module: 'performance', action: 'create', resource: 'reviews' },
      ...['view', 'create', 'delete', 'share'].map((a) => ({ module: 'files', action: a, resource: 'files' })),
      ...['view', 'create', 'edit'].map((a) => ({ module: 'compensation', action: a, resource: 'salary' })),
      ...['view', 'create'].map((a) => ({ module: 'compensation', action: a, resource: 'payslips' })),
      ...['view', 'create'].map((a) => ({ module: 'compensation', action: a, resource: 'appraisals' })),
      { module: 'compensation', action: 'view', resource: 'salary_components' },
      { module: 'compensation', action: 'export', resource: 'compensation' },
      ...['view', 'create', 'edit'].flatMap((a) => ['job_openings', 'candidates', 'interviews'].map((r) => ({ module: 'recruitment', action: a, resource: r }))),
      ...['view', 'create'].flatMap((a) => ['assessments', 'referrals', 'offer_letters'].map((r) => ({ module: 'recruitment', action: a, resource: r }))),
      { module: 'recruitment', action: 'view', resource: 'pipeline_stages' },
      ...['view', 'create', 'edit'].map((a) => ({ module: 'onboarding', action: a, resource: 'onboarding' })),
      { module: 'onboarding', action: 'view', resource: 'templates' },
      ...['view', 'create', 'approve', 'edit'].map((a) => ({ module: 'offboarding', action: a, resource: 'offboarding' })),
      { module: 'offboarding', action: 'view', resource: 'offboarding_templates' },
      { module: 'reports', action: 'view', resource: 'reports' },
      { module: 'reports', action: 'export', resource: 'reports' },
      { module: 'dashboard', action: 'view', resource: 'dashboard' },
    ],
  },
  {
    name: 'Manager / Team Lead',
    description: 'View own + reportees. Assign goals/tasks, manage delegations. No recruitment, settings, or compensation (except own).',
    permissions: [
      { module: 'employee_management', action: 'view', resource: 'employees' },
      { module: 'employee_management', action: 'view', resource: 'departments' },
      { module: 'employee_management', action: 'view', resource: 'designations' },
      { module: 'employee_management', action: 'view', resource: 'groups' },
      { module: 'employee_management', action: 'view', resource: 'projects' },
      { module: 'employee_management', action: 'create', resource: 'projects' },
      { module: 'employee_management', action: 'edit', resource: 'projects' },
      ...['view', 'create', 'edit', 'delete'].map((a) => ({ module: 'employee_management', action: a, resource: 'delegations' })),
      { module: 'employee_management', action: 'view', resource: 'reporting_hierarchy' },
      { module: 'leave', action: 'view', resource: 'leave_requests' },
      { module: 'leave', action: 'create', resource: 'leave_requests' },
      { module: 'leave', action: 'cancel', resource: 'leave_requests' },
      { module: 'leave', action: 'view', resource: 'holidays' },
      { module: 'attendance', action: 'view', resource: 'attendance' },
      { module: 'attendance', action: 'view', resource: 'team_attendance' },
      { module: 'attendance', action: 'create', resource: 'regularizations' },
      { module: 'attendance', action: 'view', resource: 'work_schedule' },
      { module: 'time_tracker', action: 'view', resource: 'time_logs' },
      ...['view', 'create', 'edit', 'delete'].map((a) => ({ module: 'performance', action: a, resource: 'goals' })),
      { module: 'performance', action: 'view', resource: 'review_cycles' },
      { module: 'performance', action: 'view', resource: 'reviews' },
      { module: 'performance', action: 'create', resource: 'reviews' },
      ...['view', 'create', 'delete', 'share'].map((a) => ({ module: 'files', action: a, resource: 'files' })),
      { module: 'compensation', action: 'view', resource: 'salary' },
      { module: 'compensation', action: 'view', resource: 'payslips' },
      { module: 'dashboard', action: 'view', resource: 'dashboard' },
    ],
  },
  {
    name: 'Employee',
    description: 'View own profile, leave, attendance, goals, files, compensation. Apply for leave, update goal progress, upload files, submit resignation.',
    permissions: [
      { module: 'employee_management', action: 'view', resource: 'employees' },
      { module: 'employee_management', action: 'view', resource: 'departments' },
      { module: 'employee_management', action: 'view', resource: 'designations' },
      { module: 'leave', action: 'view', resource: 'leave_requests' },
      { module: 'leave', action: 'create', resource: 'leave_requests' },
      { module: 'leave', action: 'cancel', resource: 'leave_requests' },
      { module: 'leave', action: 'view', resource: 'holidays' },
      { module: 'attendance', action: 'view', resource: 'attendance' },
      { module: 'attendance', action: 'create', resource: 'regularizations' },
      { module: 'attendance', action: 'view', resource: 'work_schedule' },
      { module: 'time_tracker', action: 'view', resource: 'time_logs' },
      { module: 'performance', action: 'view', resource: 'goals' },
      { module: 'performance', action: 'edit', resource: 'goals' },
      { module: 'performance', action: 'view', resource: 'reviews' },
      ...['view', 'create', 'delete'].map((a) => ({ module: 'files', action: a, resource: 'files' })),
      { module: 'compensation', action: 'view', resource: 'salary' },
      { module: 'compensation', action: 'view', resource: 'payslips' },
      { module: 'compensation', action: 'view', resource: 'appraisals' },
      { module: 'offboarding', action: 'create', resource: 'offboarding' },
      { module: 'offboarding', action: 'view', resource: 'offboarding' },
      { module: 'dashboard', action: 'view', resource: 'dashboard' },
    ],
  },
];

export const DEFAULT_LEAVE_TYPES = [
  { name: 'Casual Leave', code: 'CL', color: '#4CAF50', icon: 'sun', isPaid: true, maxConsecutiveDays: 3 },
  { name: 'Earned Leave', code: 'EL', color: '#2196F3', icon: 'calendar', isPaid: true, maxConsecutiveDays: null },
  { name: 'Leave Without Pay', code: 'LWP', color: '#FF9800', icon: 'alert-circle', isPaid: false, maxConsecutiveDays: null },
  { name: 'Paternity Leave', code: 'PL', color: '#9C27B0', icon: 'baby', isPaid: true, maxConsecutiveDays: 15 },
  { name: 'Sabbatical Leave', code: 'SL', color: '#607D8B', icon: 'briefcase', isPaid: false, maxConsecutiveDays: null },
  { name: 'Sick Leave', code: 'SKL', color: '#F44336', icon: 'thermometer', isPaid: true, maxConsecutiveDays: null },
];

export const DEFAULT_WORK_SCHEDULE = {
  name: 'General',
  startTime: '09:00',
  endTime: '18:00',
  workingDays: ['mon', 'tue', 'wed', 'thu', 'fri'],
  gracePeriodMinutes: 15,
  minHoursFullDay: 8,
  minHoursHalfDay: 4,
  overtimeThresholdHours: 9,
  isDefault: true,
};

export const DEFAULT_CANDIDATE_STAGES = [
  { name: 'New', orderIndex: 0, color: '#9E9E9E', isDefault: true },
  { name: 'In Review', orderIndex: 1, color: '#2196F3', isDefault: false },
  { name: 'Available', orderIndex: 2, color: '#00BCD4', isDefault: false },
  { name: 'Engaged', orderIndex: 3, color: '#FF9800', isDefault: false },
  { name: 'Offered', orderIndex: 4, color: '#9C27B0', isDefault: false },
  { name: 'Hired', orderIndex: 5, color: '#4CAF50', isDefault: false },
  { name: 'Rejected', orderIndex: 6, color: '#F44336', isDefault: false },
];

/** PRD 23.1 — Notification types with default in-app/email settings */
export const DEFAULT_NOTIFICATION_SETTINGS: {
  notificationType: string;
  inAppEnabled: boolean;
  emailEnabled: boolean;
}[] = [
  { notificationType: 'employee_account_created', inAppEnabled: true, emailEnabled: true },
  { notificationType: 'leave_request_submitted', inAppEnabled: true, emailEnabled: true },
  { notificationType: 'leave_request_approved', inAppEnabled: true, emailEnabled: true },
  { notificationType: 'leave_request_rejected', inAppEnabled: true, emailEnabled: true },
  { notificationType: 'leave_request_cancelled', inAppEnabled: true, emailEnabled: true },
  { notificationType: 'goal_assigned', inAppEnabled: true, emailEnabled: true },
  { notificationType: 'goal_progress_updated', inAppEnabled: true, emailEnabled: true },
  { notificationType: 'goal_completed', inAppEnabled: true, emailEnabled: true },
  { notificationType: 'task_assigned', inAppEnabled: true, emailEnabled: true },
  { notificationType: 'task_status_updated', inAppEnabled: true, emailEnabled: false },
  { notificationType: 'delegation_created', inAppEnabled: true, emailEnabled: true },
  { notificationType: 'review_cycle_started', inAppEnabled: true, emailEnabled: true },
  { notificationType: 'review_submitted', inAppEnabled: true, emailEnabled: true },
  { notificationType: 'interview_scheduled', inAppEnabled: true, emailEnabled: true },
  { notificationType: 'interview_cancelled', inAppEnabled: true, emailEnabled: true },
  { notificationType: 'candidate_stage_changed', inAppEnabled: true, emailEnabled: false },
  { notificationType: 'assessment_sent', inAppEnabled: false, emailEnabled: true },
  { notificationType: 'offer_letter_sent', inAppEnabled: false, emailEnabled: true },
  { notificationType: 'resignation_submitted', inAppEnabled: true, emailEnabled: true },
  { notificationType: 'resignation_approved_rejected', inAppEnabled: true, emailEnabled: true },
  { notificationType: 'clearance_completed', inAppEnabled: true, emailEnabled: true },
  { notificationType: 'onboarding_triggered', inAppEnabled: true, emailEnabled: true },
  { notificationType: 'onboarding_completed', inAppEnabled: true, emailEnabled: true },
  { notificationType: 'file_shared', inAppEnabled: true, emailEnabled: false },
  { notificationType: 'payslip_generated', inAppEnabled: true, emailEnabled: true },
  { notificationType: 'appraisal_recorded', inAppEnabled: true, emailEnabled: true },
  { notificationType: 'attendance_anomaly', inAppEnabled: true, emailEnabled: false },
  { notificationType: 'overtime_logged', inAppEnabled: true, emailEnabled: false },
  { notificationType: 'regularization_requested', inAppEnabled: true, emailEnabled: true },
  { notificationType: 'regularization_approved_rejected', inAppEnabled: true, emailEnabled: true },
];
